### ISSUE TITLE
Swift 4.2 is not available 0.5.3

### ISSUE THREAD

**Issue by talezion** [shu223/Pulsator#48]
When are you planning to publish 0.5.3? Seems as if the specs are updates, but was never published.

**Comment by sdtaheri** [comment]
Please publish on Cocoapods.

**Comment by thedore17** [comment]
Still hasn't been updated on cocoapods.

**Comment by bill350** [comment]
See his comment here
https://github.com/shu223/Pulsator/pull/45#issuecomment-424419062

But I think this message can be ignored and the podspec submitted 🤔

**Comment by tsvidya** [comment]
This is still not available in the podspec. I still get the following error. But I change it to 4.0 instead of 4.2, the errors are gone.
/Pods/Pulsator/Pulsator/Pulsator.swift:15:75: 'UIApplicationWillEnterForeground' has been renamed to 'UIApplication.willEnterForegroundNotification'
/Pods/Pulsator/Pulsator/Pulsator.swift:16:75: 'UIApplicationDidEnterBackground' has been renamed to 'UIApplication.didEnterBackgroundNotification'
/Pods/Pulsator/Pulsator/Pulsator.swift:108:89: 'kCAMediaTimingFunctionDefault' has been renamed to 'CAMediaTimingFunctionName.default'

**Comment by shu223** [comment]
I've just published the podspec for 0.5.3 on CocoaPods! I'm sorry for this late release.
